ifneq (,$(filter nrf802154,$(USEMODULE)))
  FEATURES_REQUIRED += periph_timer
  FEATURES_REQUIRED += radio_nrf802154
  USEMODULE += luid
  USEMODULE += netdev_ieee802154
endif

ifneq (,$(filter gorm,$(USEMODULE)))
  FEATURES_REQUIRED += radio_nrfble
  USEMODULE += nrfble
endif
